[package]
name    = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xet-server"
path = "src/main.rs"

[dependencies]
common       = { path = "../common" }
db-layer     = { path = "../db-layer" }
s3-storage   = { path = "../s3-storage" }
cas-server   = { path = "../cas-server" }
hub-api      = { path = "../hub-api" }
web-ui       = { path = "../web-ui" }

tokio        = { workspace = true }
tracing      = { workspace = true }
anyhow       = { workspace = true }
axum         = { workspace = true }

tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tower-http   = { version = "0.6", features = ["trace", "cors"] }
